### ISSUE TITLE
Feature Request: Awning Control and Heat Pump

### ISSUE THREAD

**Issue by kwe1009** [rubillos/RV-Bridge#2]
I have a 2019 Tiffin and your code works great with it but I would like to be able to control my awning and heat pump.  I'm not much of a programmer and all of my attempts to make this happen have been unsuccessful at best.

**Comment by rubillos** [comment]
I'm planning to add support for awnings in a couple of months (we store our RV about an hour away so I really only get to work on this software when I'm traveling in it). Awnings are a bit tricky because the software has to estimate the position of the awning based on the amount of time since the button presses. I have some ideas on how to implement it and will be working on it on our next trip in October.

Did you create a configuration file for you Tiffin? If so I'd love to incorporate it into this project. Thanks!

**Comment by kwe1009** [comment]
Thanks.  Attached is my Tiffin file which I am still working on.  I had a
CoachProxy but the CAN bus board just died so I'm trying your solution
which I really like better.  I don't have Apple products but I'm using the
Home KIt bridge with Home Assistant and it is working great.


Michael W.

**Comment by rubillos** [comment]
I don't think GitHub has a way to add attachments to issues. (If you replied to the GitHub email any attachment would be ignored). Could you send the file to my email at randy@mac.com? Thanks!

**Comment by rubillos** [comment]
Great, got the file, thanks!
